name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Feel free to alert about any of the issues related to the code builds and efficiency, or any bugs you migh notice. Thanks!'
        pr-message: 'Here comes a pull request Yaaat!'
